<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Database_DS.aspx.cs" Inherits="Database1_CRUD.Database_DS" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Student CRUD (SqlDataSource)</title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
                    <h2>Student CRUD (SQL DataSource)</h2>

            <!-- SqlDataSource with CRUD commands -->
            <asp:SqlDataSource 
                ID="SqlDataSource1" 
                runat="server" 
                ConnectionString="<%$ ConnectionStrings:mycon %>" 
                SelectCommand="SELECT * FROM Student"
                InsertCommand="INSERT INTO Student (name, sem, city) VALUES (@name, @sem, @city)"
                UpdateCommand="UPDATE Student SET sem=@sem, city=@city WHERE name=@name"
                DeleteCommand="DELETE FROM Student WHERE name=@name">

                <InsertParameters>
                    <asp:Parameter Name="name" Type="String" />
                    <asp:Parameter Name="sem" Type="Int32" />
                    <asp:Parameter Name="city" Type="String" />
                </InsertParameters>

                <UpdateParameters>
                    <asp:Parameter Name="name" Type="String" />
                    <asp:Parameter Name="sem" Type="Int32" />
                    <asp:Parameter Name="city" Type="String" />
                </UpdateParameters>

                <DeleteParameters>
                    <asp:Parameter Name="name" Type="String" />
                </DeleteParameters>
            </asp:SqlDataSource>

            
            <!-- Insert new record -->
            Name: <asp:TextBox ID="txtName" runat="server" /><br />
            Semester: <asp:TextBox ID="txtSem" runat="server" /><br />
            City: <asp:TextBox ID="txtCity" runat="server" /><br />

            <asp:Button ID="btnInsert" runat="server" Text="Insert"
                OnClick="btnInsert_Click" />
            <br /><br />
            <!-- GridView bound to SqlDataSource -->
            <asp:GridView 
                ID="GridView1" 
                runat="server" 
                AutoGenerateColumns="False" 
                DataSourceID="SqlDataSource1"
                DataKeyNames="name" 
                AutoGenerateEditButton="True" 
                AutoGenerateDeleteButton="True">

                <Columns>
                    <asp:BoundField DataField="name" HeaderText="Name" ReadOnly="true" />
                    <asp:BoundField DataField="sem" HeaderText="Semester" />
                    <asp:BoundField DataField="city" HeaderText="City" />
                </Columns>
            </asp:GridView>

            <br />

        </div>
    </form>
</body>
</html>
